/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phalgui_Control_PlatformBackend_cmdman_native */

#ifndef _Included_phalgui_Control_PlatformBackend_cmdman_native
#define _Included_phalgui_Control_PlatformBackend_cmdman_native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phalgui_Control_PlatformBackend_cmdman_native
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_phalgui_Control_PlatformBackend_cmdman_1native_Init
  (JNIEnv *, jobject);

/*
 * Class:     phalgui_Control_PlatformBackend_cmdman_native
 * Method:    LoadApp
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_phalgui_Control_PlatformBackend_cmdman_1native_LoadApp
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     phalgui_Control_PlatformBackend_cmdman_native
 * Method:    AppStatus
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_phalgui_Control_PlatformBackend_cmdman_1native_AppStatus
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
